---
language: python

python:
- 3.8
- 3.7
- 3.6
- 3.5

script:
- python -m unittest discover -s tests

jobs:
  include:
    - name: Static analysis
      install:
      - pip install -r requirements-dev.txt
      script:
      - flake8 whatdo
      - pylint whatdo
      - bandit -r whatdo
